---
title: "About"
output: 
  html_document:
    toc: true
    toc_float: true
---

### Academic and professional experience

***Here you can find more information about my background, academic, and professional experience***

I am a first-year Master of Science student in the department of Epidemiology at Columbia University's Mailman School of Public Health. I intend to pursue to field of Psychiatric Epidemiology with an emphasis on examining mental health disparities in minority children and adolescents in urban communities. 

I am from Philadelphia, PA but currently live in Washington Heights, NY. I obtained my Bachelor of Science in Psychology at Drexel University in 2023. I have worked as a Research Assistant at the Children's Hospital of Philadelphia (CHOP) at the Center for Injury and Violence Prevention. And until recently worked as a Research/Project Coordinator for Drexel University's LADDER Lab, which looked at brain development of individuals with neurodevelopmental disorders and typical development and how they think and learn. 

In my free time I enjoy traveling to different countries, trying new foods, and spending time with my family. 

Below you will find access to my resume (containing my academic and professional experience):

<iframe
      src="images/resume.pdf"
      width="100%"
      height="600px"
      loading="lazy"
      title="PDF-file"
  ></iframe>

