---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

### Here you can find examples of various distinct plots using Instacart data

```{r, echo=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)

data("instacart")
```

```{r, echo=FALSE}
snacks_instacart = 
  instacart |> 
  filter(department == "snacks")
```

Plot #1 {data-width=800}
-----------------------------------------------------------------------

## Top 15 Most Ordered Snacks in the Snacks Department

```{r, echo=FALSE}
snacks_instacart |> 
  count(product_name) |> 
  arrange(desc(n)) |> 
  head(15) |> 
  mutate(product_name = fct_reorder(product_name, n, .desc = TRUE)) |> 
  plot_ly(
    x = ~product_name, y = ~n, color = ~product_name,
          type = "bar", 
          colors = "viridis") |> 
  layout(
    title = "Top 15 Most Ordered Snacks in the Snacks Department",
    xaxis = list(title = "Snack Name"),
    yaxis = list(title = "Number of Times Ordered")
  )
```


Plot #2 {data-width=800}
-----------------------------------------------------------------------

## Number of Snack Aisle Orders by Hour of the Day
```{r, echo=FALSE}
snacks_instacart |> 
  group_by(order_hour_of_day) |> 
  count(aisle) |> 
  plot_ly(x = ~order_hour_of_day, y = ~n,
          type = "scatter",
          mode = "markers",
          name = ~aisle) |> 
  layout(title = "Number of Snacks Aisle Orders by Hour of the Day",
         xaxis = list(title = "Hour of the Day"),
         yaxis = list(title = "Number of Snacks Aisle Orders"))
```


Plot #3 {data-width=800}
-----------------------------------------------------------------------

## Number of Add to Cart Orders by Department

```{r, echo=FALSE}
instacart |> 
  mutate(department = fct_reorder(department, add_to_cart_order)) |> 
  plot_ly(
    y = ~add_to_cart_order, color = ~department,
    type = "box", colors = "viridis"
  ) |> 
  layout(title = "Number of Add to Cart Orders by Department",
         xaxis = list(title = "Department"),
         yaxis = list(title = "Number of Add to Cart Orders"))
```

